version: '2'
services:

  # kafka: 
  #   image: landoop/fast-data-dev
  #   environment: 
  #     ADV_HOST: localhost
  #   ports: 
  #     - "9092:9092"
  #     - "8084:8083"
  #     - "8082:8082"
  #     - "8080:8081"
  #     - "3030:3030"
  #     - "2181:2181"



  kafka: 
    image: spotify/kafka
    ports: 
      - "2181:2181" 
      - "9092:9092"
    environment: 
      ADVERTISED_PORT: 9092 
      CONSUMER_THREADS: 1 
      TOPICS: "moisture-topic"

  kafkainfluxdb:
    image: kafkainfluxdb
    links: 
      - kafka
      - influxdb
    environment: 
      - kafka_host: kafka
      - kafka_topic: "moisture-topic"
      - influxdb_host: influxdb
      - influxdb_dbname: wadus


  #http://<your_docker_host_ip>:8083/
  influxdb:
    image: tutum/influxdb
    container_name: influxdb
    environment:
      PRE_CREATE_DB: wadus
    ports: 
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8090"
      - "8099"

  # http://<your_docker_host_ip>:3000/
  grafana:
    image: grafana/grafana
    container_name: grafana
    links:
      - influxdb
    ports: 
      - "3000:3000"