version: '2'
services:

  # kafka: 
  #   image: landoop/fast-data-dev
  #   environment: 
  #     ADV_HOST: localhost
  #   ports: 
  #     - "9092:9092"
  #     - "8083:8083"
  #     - "8082:8082"
  #     - "8080:8081"
  #     - "3030:3030"
  #     - "2181:2181"

  http://<your_docker_host_ip>:8083/
  influxdb:
    image: tutum/influxdb
    container_name: influxdb
    environment:
      PRE_CREATE_DB: wadus
    ports: 
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8090"
      - "8099"

  # http://<your_docker_host_ip>:3000/
  grafana:
    image: grafana/grafana
    container_name: grafana
    links:
      - kafka
    ports: 
      - "3000:3000"